### ISSUE TITLE
Msp.cs missing !

### ISSUE THREAD

**Issue by MrMonnky** [carameltora/MovieStarPlanet-Client-Source-Code-Remake#1]
Your MSP.cs is missing :)

![grafik](https://user-images.githubusercontent.com/95761229/169599483-ed0114c7-4ba9-40c4-95a4-eec86fd06a41.png)

**Comment by carameltora** [comment]
Probably an debug class, try to delete it and try again, then say me if there's still errors :)

**Comment by MrMonnky** [comment]
Still got a lots of errors :(

![grafik](https://user-images.githubusercontent.com/95761229/170675596-882dd0c1-25aa-4505-b04e-73379ab5970b.png)

**Comment by carameltora** [comment]
Problematic lol. All of these files are present in my source
as (here, AMFActorServiceForWeb: scripts/com/moviestarplanet/AMFActorServiceForWeb)
and scripts, the script folder...

right, i recently tried this code on repl and i got the same errors, 
i'll see to make a new one fast later, and if it works, gonna make update!

**Comment by MrMonnky** [comment]
Thanks :)

**Comment by MrMonnky** [comment]
any update so far? :)

**Comment by carameltora** [comment]
Hi MrMonnky. I assume you're asking about the new checksum, as queries no longer pass through C#.
Despite translating the ActionScript3 checksum into C# several times, it hasn't worked. However, it still functions in Python, Node.js, Golang, and Rust.
A few friends and I believe that the issue could be related to FluorineFx AMF3 building operation and bytes – or perhaps the object names from the project namespace that are always present on requests.
If I manage to find a solution, I'll let you know.

**Comment by carameltora** [comment]
Other, if you have other subjects to ask about too, do not hesitate

**Comment by MrMonnky** [comment]
Thanks for your response. I'm wondering how to make the login function properly. I tried using your [py3msp](https://github.com/MrMonnky/py3msp) repository, but I'm having trouble getting it to work. Maybe we can chat via discord about that topic. :) DC: mmybeats
